/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.*;
import javax.swing.ImageIcon;
import model.Funko;
import model.FunkoBuilderConcreteEstilo1;
/**
 *
 * @author Julian Castro
 */
public class FunkoView extends javax.swing.JFrame {

    private EventManager em = new EventManager();
    /**
     * Creates new form FunkoView
     */
    public FunkoView() {
        super("FUNKO");
        initComponents();
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1icon = new javax.swing.JLabel();
        jLabelOjos = new javax.swing.JLabel();
        jLabelCamisa = new javax.swing.JLabel();
        jLabelPiernas = new javax.swing.JLabel();
        jLabelZapatos = new javax.swing.JLabel();
        jLabelFunkoBlank = new javax.swing.JLabel();
        jComboBoxOjos = new javax.swing.JComboBox<>();
        jComboBoxZapatos = new javax.swing.JComboBox<>();
        jComboBoxCabeza = new javax.swing.JComboBox<>();
        jComboBoxTorso1 = new javax.swing.JComboBox<>();
        jComboBoxPiernas1 = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButtonBuilder1 = new javax.swing.JButton();
        jButtonBuilder2 = new javax.swing.JButton();
        jButtonBuilder3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CAJA FUNKO2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 910));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CAJA FUNKO2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -30, 700, 910));
        getContentPane().add(jLabel1icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 460, 390));
        getContentPane().add(jLabelOjos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 410, 120));
        getContentPane().add(jLabelCamisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 320, 190));
        getContentPane().add(jLabelPiernas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 270, 150));
        getContentPane().add(jLabelZapatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 370, 160));

        jLabelFunkoBlank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FtpCrNRaEAEe_NJ_1.jpg"))); // NOI18N
        getContentPane().add(jLabelFunkoBlank, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 510, 750));

        jComboBoxOjos.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxOjos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jComboBoxOjos.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxOjos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sharingan", "Lentes", "Antifaz", "Ojos Locos","blank" }));
        jComboBoxOjos.setSelectedIndex(4);
        jComboBoxOjos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOjosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxOjos, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, 160, 50));

        jComboBoxZapatos.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxZapatos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jComboBoxZapatos.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxZapatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jordan IV", "JORDAN I", "CROCS", "UPTEMPO","blank" }));
        jComboBoxZapatos.setSelectedIndex(4);
        jComboBoxZapatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxZapatosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxZapatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 430, 160, 50));

        jComboBoxCabeza.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxCabeza.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jComboBoxCabeza.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxCabeza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moñito", "El nea", "BornToKill", "Avatar","blank" }));
        jComboBoxCabeza.setSelectedIndex(4);
        jComboBoxCabeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCabezaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCabeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 160, 50));

        jComboBoxTorso1.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxTorso1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jComboBoxTorso1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxTorso1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Superman", "Barca", "Nea", "Chaleco antibalas","blank" }));
        jComboBoxTorso1.setSelectedIndex(4);
        jComboBoxTorso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTorso1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTorso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 310, 160, 50));

        jComboBoxPiernas1.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxPiernas1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jComboBoxPiernas1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxPiernas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faldita", "Short Nike", "Tactical Pants", "Para Tienda","blank" }));
        jComboBoxPiernas1.setSelectedIndex(4);
        jComboBoxPiernas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPiernas1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPiernas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 160, 50));

        jTextFieldNombre.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNombre.setText("NAME");
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 570, 110));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("RESET PROTOTYPE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 790, 290, 70));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 180, 70));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 300, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 300, -1, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, -1, -1));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 420, -1, -1));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("  BUILDERS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, 160, 50));

        jButtonBuilder1.setBackground(new java.awt.Color(51, 51, 51));
        jButtonBuilder1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonBuilder1.setForeground(new java.awt.Color(204, 204, 204));
        jButtonBuilder1.setText("Build 1");
        jButtonBuilder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuilder1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuilder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 140, 50));

        jButtonBuilder2.setBackground(new java.awt.Color(51, 51, 51));
        jButtonBuilder2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonBuilder2.setForeground(new java.awt.Color(204, 204, 204));
        jButtonBuilder2.setText("Build militar");
        jButtonBuilder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuilder2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuilder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 640, 140, 50));

        jButtonBuilder3.setBackground(new java.awt.Color(51, 51, 51));
        jButtonBuilder3.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButtonBuilder3.setForeground(new java.awt.Color(204, 204, 204));
        jButtonBuilder3.setText("PARA LOS PELITOS");
        jButtonBuilder3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuilder3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuilder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 640, 140, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flat-cartoon-comic-background-pop-art-comic-background-fight-backgrounds-comics-style-design-illustration-free-vector.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxOjosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOjosActionPerformed
        // COMBO BOX PARA LOS OJOS
        ImageIcon nuevaImagen = em.cambiar_OJOSFunko(jComboBoxOjos.getSelectedIndex());
        jLabelOjos.setIcon(nuevaImagen);
    }//GEN-LAST:event_jComboBoxOjosActionPerformed

    private void jComboBoxZapatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxZapatosActionPerformed
        // COMBO BOX PARA LA CABEZA
        ImageIcon nuevaImagen = em.cambiar_Zapatos(jComboBoxZapatos.getSelectedIndex());
        jLabelZapatos.setIcon(nuevaImagen);
    }//GEN-LAST:event_jComboBoxZapatosActionPerformed

    private void jComboBoxCabezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCabezaActionPerformed
        // TODO add your handling code here:
        ImageIcon nuevaImagen = em.cambiar_cabezaFunko(jComboBoxCabeza.getSelectedIndex());
        jLabel1icon.setIcon(nuevaImagen);
        
    }//GEN-LAST:event_jComboBoxCabezaActionPerformed

    private void jComboBoxTorso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTorso1ActionPerformed
        // TODO add your handling code here:
        ImageIcon nuevaImagen = em.cambiar_Torso(jComboBoxTorso1.getSelectedIndex());
        jLabelCamisa.setIcon(nuevaImagen);
        
    }//GEN-LAST:event_jComboBoxTorso1ActionPerformed

    private void jComboBoxPiernas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPiernas1ActionPerformed
        // TODO add your handling code here:
        ImageIcon nuevaImagen = em.cambiar_Piernas(jComboBoxPiernas1.getSelectedIndex());
        jLabelPiernas.setIcon(nuevaImagen);
    }//GEN-LAST:event_jComboBoxPiernas1ActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Funko f;
        f = em.PrototypeBlank();
        
        ImageIcon cabeza = new ImageIcon(getClass().getResource(f.getCabeza()));
        jLabel1icon.setIcon(cabeza);
        
        ImageIcon Ojos = new ImageIcon(getClass().getResource(f.getOjos()));
        jLabelOjos.setIcon(Ojos);
        
        ImageIcon Torso = new ImageIcon(getClass().getResource(f.getTorso()));
        jLabelCamisa.setIcon(Torso);
        
        ImageIcon Piernas = new ImageIcon(getClass().getResource(f.getPiernas()));
        jLabelPiernas.setIcon(Piernas);
        
        ImageIcon Zapatos = new ImageIcon(getClass().getResource(f.getZapatos()));
        jLabelZapatos.setIcon(Zapatos);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBuilder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuilder1ActionPerformed
        // TODO add your handling code here:
        Funko funko;
        funko = em.Builder1ToViewFunko();
        jTextFieldNombre.setText("ESTILO NIÑA SUPERMAN NARUTO");
             
        ImageIcon cabeza = new ImageIcon(getClass().getResource(funko.getCabeza()));
        jLabel1icon.setIcon(cabeza);
        
        ImageIcon Ojos = new ImageIcon(getClass().getResource(funko.getOjos()));
        jLabelOjos.setIcon(Ojos);
        
        ImageIcon Torso = new ImageIcon(getClass().getResource(funko.getTorso()));
        jLabelCamisa.setIcon(Torso);
        
        ImageIcon Piernas = new ImageIcon(getClass().getResource(funko.getPiernas()));
        jLabelPiernas.setIcon(Piernas);
        
        ImageIcon Zapatos = new ImageIcon(getClass().getResource(funko.getZapatos()));
        jLabelZapatos.setIcon(Zapatos);
    }//GEN-LAST:event_jButtonBuilder1ActionPerformed

    private void jButtonBuilder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuilder2ActionPerformed
        // TODO add your handling code here:
        Funko funko;
        funko = em.Builder2ToViewFunko();
        jTextFieldNombre.setText("MILITAR");
             
        ImageIcon cabeza = new ImageIcon(getClass().getResource(funko.getCabeza()));
        jLabel1icon.setIcon(cabeza);
        
        ImageIcon Ojos = new ImageIcon(getClass().getResource(funko.getOjos()));
        jLabelOjos.setIcon(Ojos);
        
        ImageIcon Torso = new ImageIcon(getClass().getResource(funko.getTorso()));
        jLabelCamisa.setIcon(Torso);
        
        ImageIcon Piernas = new ImageIcon(getClass().getResource(funko.getPiernas()));
        jLabelPiernas.setIcon(Piernas);
        
        ImageIcon Zapatos = new ImageIcon(getClass().getResource(funko.getZapatos()));
        jLabelZapatos.setIcon(Zapatos);
             
    }//GEN-LAST:event_jButtonBuilder2ActionPerformed

    private void jButtonBuilder3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuilder3ActionPerformed
        // TODO add your handling code here:
        Funko funko;
        funko = em.Builder3ToViewFunko();
        jTextFieldNombre.setText("FARRA");
             
        ImageIcon cabeza = new ImageIcon(getClass().getResource(funko.getCabeza()));
        jLabel1icon.setIcon(cabeza);
        
        ImageIcon Ojos = new ImageIcon(getClass().getResource(funko.getOjos()));
        jLabelOjos.setIcon(Ojos);
        
        ImageIcon Torso = new ImageIcon(getClass().getResource(funko.getTorso()));
        jLabelCamisa.setIcon(Torso);
        
        ImageIcon Piernas = new ImageIcon(getClass().getResource(funko.getPiernas()));
        jLabelPiernas.setIcon(Piernas);
        
        ImageIcon Zapatos = new ImageIcon(getClass().getResource(funko.getZapatos()));
        jLabelZapatos.setIcon(Zapatos);
        
    }//GEN-LAST:event_jButtonBuilder3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FunkoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FunkoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FunkoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FunkoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FunkoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButtonBuilder1;
    public javax.swing.JButton jButtonBuilder2;
    public javax.swing.JButton jButtonBuilder3;
    public javax.swing.JComboBox<String> jComboBoxCabeza;
    public javax.swing.JComboBox<String> jComboBoxOjos;
    public javax.swing.JComboBox<String> jComboBoxPiernas1;
    public javax.swing.JComboBox<String> jComboBoxTorso1;
    public javax.swing.JComboBox<String> jComboBoxZapatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1icon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCamisa;
    private javax.swing.JLabel jLabelFunkoBlank;
    public javax.swing.JLabel jLabelOjos;
    public javax.swing.JLabel jLabelPiernas;
    private javax.swing.JLabel jLabelZapatos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
