/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.EventManager;
import javax.swing.ImageIcon;
import model.Lego;
import model.SingletonCaraExclusiva;

/**
 *
 * @author Julian Castro
 */
public class LegoView extends javax.swing.JFrame {

    EventManager em = new EventManager();
    /**
     * Creates new form LegoView
     */
    public LegoView() {
        super("LEGO");
        initComponents();
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCabezaLego = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxOjos1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxTorso = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jComboBoxPiernas = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabelPiernas = new javax.swing.JLabel();
        jLabelCabeza = new javax.swing.JLabel();
        jLabelCara = new javax.swing.JLabel();
        jLabelTorso = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxCabezaLego.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxCabezaLego.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jComboBoxCabezaLego.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxCabezaLego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hair 1", "Hair 2", "Hair 3", "MasterChief","blank" }));
        jComboBoxCabezaLego.setSelectedIndex(4);
        jComboBoxCabezaLego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCabezaLegoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCabezaLego, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 160, 50));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("EXCLUSIVE ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 750, 140, 50));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 180, 70));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxOjos1.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxOjos1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jComboBoxOjos1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxOjos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cara UwU", "Saitama", "Cara facha", "Creeper","blank" }));
        jComboBoxOjos1.setSelectedIndex(4);
        jComboBoxOjos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOjos1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxOjos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 180, 70));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jComboBoxTorso.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxTorso.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jComboBoxTorso.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxTorso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camisa Creeper", "Camisa777", "Smokin", "En bola","blank" }));
        jComboBoxTorso.setSelectedIndex(4);
        jComboBoxTorso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTorsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTorso, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTorso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 70));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jComboBoxPiernas.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxPiernas.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jComboBoxPiernas.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxPiernas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verde", "Negro", "Azul", "En bola","blank" }));
        jComboBoxPiernas.setSelectedIndex(4);
        jComboBoxPiernas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPiernasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxPiernas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxPiernas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("BUILD 1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 150, 80));
        getContentPane().add(jLabelPiernas, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 290, 300));
        getContentPane().add(jLabelCabeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 290, 250));
        getContentPane().add(jLabelCara, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 210, 180));
        getContentPane().add(jLabelTorso, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 285, 500, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png-transparent-lego-illustration-lego-minifigure-template-lego-creator-blank-person-outline-angle-white-child.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 540, 770));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoFunko.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 790, 880));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("SINGLETON");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 730, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flat-cartoon-comic-background-pop-art-comic-background-fight-backgrounds-comics-style-design-illustration-free-vector.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -20, 1630, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCabezaLegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCabezaLegoActionPerformed
        // TODO add your handling code here:
        ImageIcon nuevaImagen = em.cambiar_cabezaLego(jComboBoxCabezaLego.getSelectedIndex());
        jLabelCabeza.setIcon(nuevaImagen);

    }//GEN-LAST:event_jComboBoxCabezaLegoActionPerformed

    private void jComboBoxOjos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOjos1ActionPerformed
        // TODO add your handling code here:
        ImageIcon nuevaImagen = em.cambiar_OjosLEGO(jComboBoxOjos1.getSelectedIndex());
        jLabelCara.setIcon(nuevaImagen);
    }//GEN-LAST:event_jComboBoxOjos1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SingletonCaraExclusiva s;
        s = em.caraExclusivaLego();
        
        ImageIcon ojos = new ImageIcon(getClass().getResource(s.getOjos()));
        jLabelCara.setIcon(ojos);
        //ImageIcon piernas = new ImageIcon(getClass().getResource(s.getPiernas()));
        //jLabel.setIcon(piernas);
        ImageIcon torso = new ImageIcon(getClass().getResource(s.getTorso()));
        jLabelTorso.setIcon(torso);
        ImageIcon cabeza = new ImageIcon(getClass().getResource(s.getCabeza()));
        jLabelCabeza.setIcon(cabeza);
        ImageIcon piernas = new ImageIcon(getClass().getResource(s.getPiernas()));
        jLabelPiernas.setIcon(piernas);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxTorsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTorsoActionPerformed
        // TODO add your handling code here:
        ImageIcon nuevaImagen = em.cambiar_torsoLego(jComboBoxTorso.getSelectedIndex());
        jLabelTorso.setIcon(nuevaImagen);
    }//GEN-LAST:event_jComboBoxTorsoActionPerformed

    private void jComboBoxPiernasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPiernasActionPerformed
        // TODO add your handling code here:
        ImageIcon nuevaImagen = em.cambiar_PiernasLEGO(jComboBoxPiernas.getSelectedIndex());
        jLabelPiernas.setIcon(nuevaImagen);
    }//GEN-LAST:event_jComboBoxPiernasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Lego lego;
        lego = em.Builder1ToViewLEGO1();
        
        ImageIcon cabeza = new ImageIcon(getClass().getResource(lego.getCabeza()));
        jLabelCabeza.setIcon(cabeza);
        
        ImageIcon ojos = new ImageIcon(getClass().getResource(lego.getOjos()));
        jLabelCara.setIcon(ojos);
        
        ImageIcon torso = new ImageIcon(getClass().getResource(lego.getPiernas()));
        jLabelTorso.setIcon(torso);
        
        ImageIcon piernas = new ImageIcon(getClass().getResource(lego.getTorso()));
        jLabelPiernas.setIcon(piernas);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LegoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LegoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LegoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LegoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LegoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JComboBox<String> jComboBoxCabezaLego;
    public javax.swing.JComboBox<String> jComboBoxOjos1;
    public javax.swing.JComboBox<String> jComboBoxPiernas;
    public javax.swing.JComboBox<String> jComboBoxTorso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCabeza;
    private javax.swing.JLabel jLabelCara;
    private javax.swing.JLabel jLabelPiernas;
    private javax.swing.JLabel jLabelTorso;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
